name: CI build and run unit tests

on: [push]

jobs:
  build_and_unittest:
    name: Build and Run Unit Tests

    runs-on: windows-latest

    steps:

    # Checkout source code from the repo.
    - uses: actions/checkout@v2

    # Setup the .Net Core SDK (dotnet CLI to use).
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102

    # Build the solution.
    - name: Build solution with dotnet
      run: dotnet build --configuration Release

    # Run the unit tests.
    - name: Run unit tests
      run: dotnet test
